filebeat.inputs:
  
- type: filestream 
  id: filestream-logs
  paths:
    - /var/log/minitwit/*.log
  parsers:
    - ndjson:
      overwrite_keys: true 
      add_error_key: true 
      expand_keys: true

output.elasticsearch:
  hosts: ['http://159.223.18.85:9200']
  indices:
    - index: "filebeat-elastic-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.or:
        - equals:
            container.image.name: docker.elastic.co/beats/filebeat:7.2.0
        - equals:
            container.image.name: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
        - equals:
            container.image.name: docker.elastic.co/kibana/kibana:7.2.0
    - index: "filebeat-minitwit-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.or:
          - equals:
              container.image.name: minitwit
    - index: "all"
filebeat.modules.system.process.cgroups.enabled: false
filebeat.modules: []
logging.json: true
logging.metrics.enabled: false