version: '3.3'

volumes:
    elk_elasticsearch_data:
networks:
  main:

services:
  minitwitimage:
    build:
      context: .
      dockerfile: itu-minitwit-node/Dockerfile
    image: minitwitimage
    container_name: minitwit
    ports:
        - '3000:3000'
    networks:
      - main
    volumes:
      - elk_elasticsearch_data:/app/logs
      #- /app/logs:/app/logs
      
  filebeat:
    build:
      context: .
      dockerfile: filebeat/Dockerfile
    image: filebeat
    container_name: filebeat
    command: filebeat -e -strict.perms=false
    networks:
      - main
    environment:
      user: root
    volumes:
      - ./filebeat/filebeat.yml:/etc/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - elk_elasticsearch_data:/app/logs
      #- /app/logs:/app/logs


  flagtool:
    build:
      context: .
      dockerfile: flag_tool/Dockerfile
    image: flag-tool
    container_name: flag-tool
    command: tail -f /dev/null
    networks:
      - main