version: '3.3'

networks:
  elk:

services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.1"
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
        - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        - "discovery.type=single-node"
    networks:
        - elk
    mem_limit: 2g

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.17.1"
    container_name: kibana
    environment:
        elasticsearch.hosts: '["http://elasticsearch:9200"]'
         # Increase startup timeout to 5 minutes
        ELASTICSEARCH_STARTUP_TIMEOUT: 300000
    ports:
      - "5601:5601"
    networks:
        - elk
    depends_on:
      - elasticsearch