version: '3.5'

networks:
  main:

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - main
    volumes:
      - ./prometheus/prometheus-monitoring.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    image: minitwit/grafana
    ports:
      - 3005:3000
    networks:
      - main
    depends_on:
      - prometheus