name: Automatic Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
